export type PlantRecord = {
  id: string;
  common: string;
  scientific: string;
  family: string;
};

export const plantRecords: PlantRecord[] = [
  { id: "item-1", common: "Linh chi", scientific: "Ganoderma lucidum (Curtis) P. Karst", family: "Ganodermataceae (Linh chi)" },
  { id: "item-2", common: "Đại hồi", scientific: "Illicium verum Hook.f.", family: "Illiciaceae (Hồi)" },
  { id: "item-3", common: "Quế", scientific: "Cinnamomum cassia (L.) J.Presl", family: "Lauraceae (Long não)" },
  { id: "item-4", common: "Sen", scientific: "Nelumbo nucifera Gaertn.", family: "Nelumbonaceae (Sen)" },
  { id: "item-5", common: "Bình vôi", scientific: "Stephania glabra (Roxb.) Miers", family: "Menispermaceae (Tiết dê)" },
  { id: "item-6", common: "Hoàng liên", scientific: "Coptis chinensis Franch.", family: "Ranunculaceae (Hoàng liên)" },
  { id: "item-7", common: "Ô đầu", scientific: "Aconitum carmichaelii Debeaux", family: "Ranunculaceae (Hoàng liên)" },
  { id: "item-8", common: "Ngưu tất", scientific: "Achyranthes bidentata Blume", family: "Amaranthaceae (Rau dền)" },
  { id: "item-9", common: "Hà thủ ô đỏ", scientific: "Fallopia multiflora (Thunb.) Haraldson", family: "Polygonaceae (Rau răm)" },
  { id: "item-10", common: "Đỗ trọng", scientific: "Eucommia ulmoides Oliv.", family: "Eucommiaceae (Đỗ trọng)" },
  { id: "item-11", common: "Dâu tằm", scientific: "Morus alba L.", family: "Moraceae (Dâu tằm)" },
  { id: "item-12", common: "Gai", scientific: "Boehmeria nivea (L.) Gaudich.", family: "Urticaceae (Gai)" },
  { id: "item-13", common: "Khổ sâm", scientific: "Croton tonkinensis Gagnep.", family: "Euphorbiaceae (Thầu dầu)" },
  { id: "item-14", common: "Chó đẻ răng cưa", scientific: "Phyllanthus urinaria L.", family: "Euphorbiaceae (Thầu dầu)" },
  { id: "item-15", common: "Tràm", scientific: "Melaleuca cajuputi Powell", family: "Myrtaceae (Sim)" },
  { id: "item-16", common: "Kim tiền thảo", scientific: "Desmodium styracifolium (Osbeck) Merr.", family: "Fabaceae (Đậu)" },
  { id: "item-17", common: "Hòe", scientific: "Styphnolobium japonicum (L.) Schott", family: "Fabaceae (Đậu)" },
  { id: "item-18", common: "Sắn dây", scientific: "Pueraria thomsonii Benth.", family: "Fabaceae (Đậu)" },
  { id: "item-19", common: "Hoàng bá", scientific: "Phellodendronchinense C. K. Schneid", family: "Rutaceae (Cam)" },
  { id: "item-20", common: "Lạc tiên", scientific: "Passiflora foetida L.", family: "Passifloraceae (Lạc tiên)" },
  { id: "item-21", common: "Sâm Ngọc Linh", scientific: "Panax vietnamensis Ha & Grushv.", family: "Araliaceae (Nhân sâm)" },
  { id: "item-22", common: "Đinh lăng", scientific: "Polyscias fruticosa (L.) Harms", family: "Araliaceae (Nhân sâm)" },
  { id: "item-23", common: "Tam thất", scientific: "Panax notoginseng (Burkill) F. H. Chen", family: "Araliaceae (Nhân sâm)" },
  { id: "item-24", common: "Đương quy", scientific: "Angelica sinensis (Oliv.) Diels", family: "Apiaceae (Cần)" },
  { id: "item-25", common: "Bạch chỉ", scientific: "Angelica dahurica (Hoffm.) Benth. & Hook.f. ex Franch. & Sav.", family: "Apiaceae (Cần)" },
  { id: "item-26", common: "Rau má", scientific: "Centella asiatica (L.) Urb.", family: "Apiaceae (Cần)" },
  { id: "item-27", common: "Kim ngân", scientific: "Lonicera japonica Thunb.", family: "Caprifoliaceae (Cơm cháy)" },
  { id: "item-28", common: "Tục đoạn", scientific: "Dipsacus japonicus Miq.", family: "Dipsacaceae (Tục đoạn)" },
  { id: "item-29", common: "Dành dành", scientific: "Gardenia jasminoides J.Ellis", family: "Rubiaceae (Cà phê)" },
  { id: "item-30", common: "Ba kích", scientific: "Morinda officinalis F.C.How", family: "Rubiaceae (Cà phê)" },
  { id: "item-31", common: "Mã tiền", scientific: "Strychnos nux-vomica L.", family: "Loganiaceae (Mã tiền)" },
  { id: "item-32", common: "Dừa cạn", scientific: "Catharanthus roseus (L.) G.Don", family: "Apocynaceae (Trúc đào)" },
  { id: "item-33", common: "Cà gai leo", scientific: "Solanum procumbens Lour.", family: "Solanaceae (Cà)" },
  { id: "item-34", common: "Cà độc dược", scientific: "Datura metel L.", family: "Solanaceae (Cà)" },
  { id: "item-35", common: "Nhân trần", scientific: "Adenosma caeruleum R. Br.", family: "Scrophulariaceae (Hoa mõm chó)" },
  { id: "item-36", common: "Địa hoàng", scientific: "Rehmannia glutinosa (Gaertn.) DC.", family: "Scrophulariaceae (Hoa mõm chó)" },
  { id: "item-37", common: "Mã đề", scientific: "Plantago major L.", family: "Plantaginaceae (Mã đề)" },
  { id: "item-38", common: "Xuyên tâm liên", scientific: "Andrographis paniculata (Burm.f.) Nees", family: "Acanthaceae (Ô rô)" },
  { id: "item-39", common: "Bạch đồng nữ", scientific: "Clerodendrum chinense var. simplex (Moldenke) S.L.Chen", family: "Verbenaceae (Cỏ roi ngựa)" },
  { id: "item-40", common: "Ích mẫu", scientific: "Leonurus japonicus Houtt.", family: "Lamiaceae (Bạc hà)" },
  { id: "item-41", common: "Bạc hà", scientific: "Mentha arvensis L.", family: "Lamiaceae (Bạc hà)" },
  { id: "item-42", common: "Hương nhu trắng", scientific: "Ocimum gratissimum L.", family: "Lamiaceae (Bạc hà)" },
  { id: "item-43", common: "Đảng sâm", scientific: "Codonopsis javanica (Blume) Hook.f. & Thomson", family: "Campanulaceae (Hoa chuông)" },
  { id: "item-44", common: "Cát cánh", scientific: "Platycodon grandiflorus (Jacq.) A.DC.", family: "Campanulaceae (Hoa chuông)" },
  { id: "item-45", common: "Ngải cứu", scientific: "Artemisia vulgaris L.", family: "Asteraceae (Cúc)" },
  { id: "item-46", common: "Cúc hoa vàng", scientific: "Chrysanthemum indicum L.", family: "Asteraceae (Cúc)" },
  { id: "item-47", common: "Actisô", scientific: "Cynara scolymus L.", family: "Asteraceae (Cúc)" },
  { id: "item-48", common: "Cỏ nhọ nồi", scientific: "Eclipta prostrata (L.) L.", family: "Asteraceae (Cúc)" },
  { id: "item-49", common: "Sài đất", scientific: "Wedelia chinensis (Oscbeck) Merr.", family: "Asteraceae (Cúc)" },
  { id: "item-50", common: "Xạ can", scientific: "Belamcanda chinensis (L.) DC.", family: "Iridaceae (La dơn)" },
  { id: "item-51", common: "Trinh nữ hòang cung", scientific: "Crinum latifolium L.", family: "Amaryllidaceae (Náng)" },
  { id: "item-52", common: "Thiên môn đông", scientific: "Asparagus cochinchinensis (Lour.) Merr.", family: "Asparagaceae (Thiên môn)" },
  { id: "item-53", common: "Hoài sơn", scientific: "Dioscorea persimilis Prain & Burkill", family: "Dioscoreaceae (Củ nâu)" },
  { id: "item-54", common: "Bách bộ", scientific: "Stemona tuberosa Lour.", family: "Stemonaceae (Bách bộ)" },
  { id: "item-55", common: "Sa nhân", scientific: "Amomum villosum Lour.", family: "Zingiberaceae (Gừng)" },
  { id: "item-56", common: "Nghệ vàng", scientific: "Curcuma longa L.", family: "Zingiberaceae (Gừng)" },
  { id: "item-57", common: "Gừng", scientific: "Zingiber officinale Roscoe", family: "Zingiberaceae (Gừng)" },
  { id: "item-58", common: "Hương phụ", scientific: "Cyperus rotundus L.", family: "Cyperaceae (Cói)" },
  { id: "item-59", common: "Ý dĩ", scientific: "Coix lacryma-jobi var. ma-yuen (Rom.Caill.) Stapf", family: "Poaceae (Lúa)" },
  { id: "item-60", common: "Thiên niên kiện", scientific: "Homalomena occulta (Lour.) Schott", family: "Araceae (Ráy)" }
];
